development:
  secret_key_base: <%= ENV["SECRET_KEY"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY"] %>
